FROM ros:melodic-ros-core as base

# Non Root user
ARG user_name=ros
ARG user_uid=1000
ARG user_home=/home/$user_name
ARG user_shell=/bin/bash

ENV DEBIAN_FRONTEND noninteractive

RUN useradd -m -d $user_home -s $user_shell -u $user_uid $user_name \
	&& echo "PS1='\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;33m\]\u\[\033[00m\]@\[\033[01;31m\]\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '" >> ~/.bashrc

RUN apt-get update \
	&& apt-get install -q -y \
		wget \
		apt-utils \
	&& apt-get clean -q -y \
	&& apt-get autoremove -q -y \
	&& rm -rf /var/lib/apt/lists/*

RUN apt-get update \
	&& apt upgrade -y \
	&& apt-get clean -q -y \
	&& apt-get autoremove -q -y \
	&& rm -rf /var/lib/apt/lists/*

# install ros packages
RUN apt-get update \
	&& apt-get install -q -y \
		python3-pip \
		python-catkin-tools \
		python3-vcstool \
	&& apt-get clean -q -y \
	&& apt-get autoremove -q -y \
	&& rm -rf /var/lib/apt/lists/*

ENV user_name=ros
ENV user_home=/home/$user_name

# Change of user
USER $user_name

ENV ck_dir=$user_home/catkin_ws
ENV ck_src_dir=$ck_dir/src

RUN mkdir -p $ck_src_dir
WORKDIR $ck_dir