---
# Copyright 2024 Robotnik Automation S.L.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#    1. Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#
#    2. Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#
#    3. Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived from
#       this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# Maintanier: Guillem Gari  <ggari@robotnik.es> Robotnik Automation S.L.
#
#
# Description: Container template processor.
#              This compose file launches the container template processor,
#              allowing the creation of required files on the host machine
#              without any tools installed other than Docker. It can be
#              configured via setup-container.yaml.
#
name: template-processor
services:
  container:
    image: >-
      docker.io/robotnik/template-procesor:devel
    build:
      context: ../../
      dockerfile: setup-container/container/Dockerfile
      args:
        version: devel
        image_mirror: ${IMAGE_MIRROR}
        image_tag: ${IMAGE_TAG}
        UID: ${HOST_UID}
        GID: ${HOST_GID}
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - type: bind
        source: ../../container
        target: /home/helm/output
      - type: bind
        source: ../.
        target: /home/helm/setup-container
      - type: bind
        source: ../../setup-container.yaml
        target: /home/helm/values.yaml
